export const reducerCases = {
  SET_USER_RAPID: "SET_USER_RAPID",
  SET_PLAYLISTS_RAPID: "SET_PLAYLISTS_RAPID",
  SET_PLAYING: "SET_PLAYING",
  SET_PLAYLIST_RAPID: "SET_PLAYLIST_RAPID",
  SET_PLAYLIST_ID: "SET_PLAYLIST_ID",
  SET_SEARCH_RAPID: "SET_SEARCH_RAPID",
};
